
version: 2
jobs:
    build:
        docker:
            - image: koppor/texlive
        steps:
            - run:
                name: Git settings
                command: |
                    git config --global user.email 'fujiisoup@gmail.com'
                    git config --global user.name 'fujiisoup'
            - checkout
            - run:
                name: Generating current version
                command: |
                    ./make.sh
    deploy:
        docker:
            - image: koppor/texlive
        steps:
            - run:
                name: Git settings
                command: |
                    git config --global user.email 'fujiisoup@gmail.com'
                    git config --global user.name 'fujiisoup'
            - checkout
            - run:
                name: Generating current version
                command: |
                    ./make.sh
            - run:
                name: Commit to repository
                command: |
                    git checkout -b release-pdf
                    git add -f math_note.pdf
                    git commit -m "[CircleCI] Releasing PDF @$(date +'%Y/%m/%d %I:%M') [ci skip]"
                    git push -f origin release-pdf

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
